// <auto-generated />
namespace SalePizza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BeforeDependency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeforeDependency));
        
        string IMigrationMetadata.Id
        {
            get { return "201808061128223_Before Dependency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
